### PR TITLE
Change the style: resolve fonts problem.

### PR DESCRIPTION
**Pull request by abdorah**

### CODE REVIEW

**Comment by BaseMax** [comment]
Hi thanks.

Can you run `pre-commit run --all-files` and check?

**Comment by jbampton** [comment]
I don't want this Node rubbish

**Comment by BaseMax** [comment]
> I don't want this Node rubbish

Yes, but this is pure html template. we can port this to Jekyll.

**Comment by jbampton** [comment]
You are not listening. All my work on the Cloudflare Workers was deleted.  Monorepo is needed now more than ever.  https://github.com/One-Language/Website/blob/main/.github/workflows/wrangler.yml

**Review by jbampton — CHANGES_REQUESTED** [review]
Tests need to pass

**Review by jbampton — CHANGES_REQUESTED** [review]
Pull requests must be done from a feature branch not main or master. GIT 101. https://slurp.readthedocs.io/en/latest/git.html

**Comment by abdorah** [comment]
```
Check hooks apply to the repository......................................Failed
- hook id: check-hooks-apply
- exit code: 1

check-json does not apply to this repository
check-toml does not apply to this repository
pretty-format-json does not apply to this repository

Check for case conflicts.................................................Passed
Check that executables have shebangs.....................................Failed
- hook id: check-executables-have-shebangs
- exit code: 1

.github/ISSUE_TEMPLATE/feature_request.md: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x .github/ISSUE_TEMPLATE/feature_request.md`
  If it is supposed to be executable, double-check its shebang.
.github/workflows/lint.yml: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x .github/workflows/lint.yml`
  If it is supposed to be executable, double-check its shebang.
.github/dependabot.yml: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x .github/dependabot.yml`
  If it is supposed to be executable, double-check its shebang.
.pre-commit-config.yaml: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x .pre-commit-config.yaml`
  If it is supposed to be executable, double-check its shebang.
.all-contributorsrc: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x .all-contributorsrc`
  If it is supposed to be executable, double-check its shebang.
.hound.yml: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x .hound.yml`
  If it is supposed to be executable, double-check its shebang.
.gitignore: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x .gitignore`
  If it is supposed to be executable, double-check its shebang.
.github/workflows/wrangler.yml: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x .github/workflows/wrangler.yml`
  If it is supposed to be executable, double-check its shebang.
.circleci/config.yml: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x .circleci/config.yml`
  If it is supposed to be executable, double-check its shebang.
LICENSE: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x LICENSE`
  If it is supposed to be executable, double-check its shebang.
.editorconfig: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x .editorconfig`
  If it is supposed to be executable, double-check its shebang.
.github/workflows/codeql-analysis.yml: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x .github/workflows/codeql-analysis.yml`
  If it is supposed to be executable, double-check its shebang.
.github/ISSUE_TEMPLATE/bug_report.md: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x .github/ISSUE_TEMPLATE/bug_report.md`
  If it is supposed to be executable, double-check its shebang.
.github/linters/.yaml-lint.yml: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x .github/linters/.yaml-lint.yml`
  If it is supposed to be executable, double-check its shebang.
codespell.txt: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x codespell.txt`
  If it is supposed to be executable, double-check its shebang.
CODEOWNERS: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x CODEOWNERS`
  If it is supposed to be executable, double-check its shebang.
.github/workflows/super-linter.yml: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x .github/workflows/super-linter.yml`
  If it is supposed to be executable, double-check its shebang.
.github/linters/.markdown-lint.yml: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x .github/linters/.markdown-lint.yml`
  If it is supposed to be executable, double-check its shebang.
CNAME: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x CNAME`
  If it is supposed to be executable, double-check its shebang.
README.md: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x README.md`
  If it is supposed to be executable, double-check its shebang.
```
These are the logs of the pre-commit (where it fails exactly). I cannot fix these problems, in fact, none of my previous commits has any relation to these files, and I didn't change them ever. I don't know exactly how to resolve this issue for my PR, but I can tell that maybe the pre-commits needs some changes, especially for the .github folder.

**Comment by abdorah** [comment]
The actual problem:

````
Check hooks apply to the repository......................................Failed
- hook id: check-hooks-apply
- exit code: 1

check-executables-have-shebangs does not apply to this repository
check-json does not apply to this repository
check-toml does not apply to this repository
pretty-format-json does not apply to this repository
```

**Comment by johnbampton** [comment]
Remove the 4 checks and run pre-commit again.

Those checks were for the `Cloudflare Workers` I was using.

**Comment by BaseMax** [comment]
**Merging is blocked**
Merging can be performed automatically once the requested changes are addressed. 

John, can you check this pls? @jbampton

**Review by BaseMax — APPROVED** [review]
LGTM

**Review by BaseMax — APPROVED** [review]
OK

**Review by BaseMax — APPROVED** [review]
OK

**Review by BaseMax — APPROVED** [review]
OK

**Review by BaseMax — APPROVED** [review]
OK

**Comment by jbampton** [comment]
Lots of files touched.  Seems like somewhere we lost files ??

Empty file...

**Comment by jbampton** [comment]
Screen Shot 2021-09-02 at 2 51 28 pm

Screen Shot 2021-09-02 at 2 50 43 pm

**Comment by abdorah** [comment]
Hi, what I did to those files is just I told "Check that executables have shebangs.....................................Failed" pre-commit hook to not consider them as executables.

> ```
> Check hooks apply to the repository......................................Failed
> - hook id: check-hooks-apply
> - exit code: 1
> 
> check-json does not apply to this repository
> check-toml does not apply to this repository
> pretty-format-json does not apply to this repository
> 
> Check for case conflicts.................................................Passed
> Check that executables have shebangs.....................................Failed
> - hook id: check-executables-have-shebangs
> - exit code: 1
> 
> .github/ISSUE_TEMPLATE/feature_request.md: marked executable but has no (or invalid) shebang!
>   If it isn't supposed to be executable, try: `chmod -x .github/ISSUE_TEMPLATE/feature_request.md`
>   If it is supposed to be executable, double-check its shebang.
> .github/workflows/lint.yml: marked executable but has no (or invalid) shebang!
>   If it isn't supposed to be executable, try: `chmod -x .github/workflows/lint.yml`
>   If it is supposed to be executable, double-check its shebang.
> .github/dependabot.yml: marked executable but has no (or invalid) shebang!
>   If it isn't supposed to be executable, try: `chmod -x .github/dependabot.yml`
>   If it is supposed to be executable, double-check its shebang.
> .pre-commit-config.yaml: marked executable but has no (or invalid) shebang!
>   If it isn't supposed to be executable, try: `chmod -x .pre-commit-config.yaml`
>   If it is supposed to be executable, double-check its shebang.
> .all-contributorsrc: marked executable but has no (or invalid) shebang!
>   If it isn't supposed to be executable, try: `chmod -x .all-contributorsrc`
>   If it is supposed to be executable, double-check its shebang.
> .hound.yml: marked executable but has no (or invalid) shebang!
>   If it isn't supposed to be executable, try: `chmod -x .hound.yml`
>   If it is supposed to be executable, double-check its shebang.
> .gitignore: marked executable but has no (or invalid) shebang!
>   If it isn't supposed to be executable, try: `chmod -x .gitignore`
>   If it is supposed to be executable, double-check its shebang.
> .github/workflows/wrangler.yml: marked executable but has no (or invalid) shebang!
>   If it isn't supposed to be executable, try: `chmod -x .github/workflows/wrangler.yml`
>   If it is supposed to be executable, double-check its shebang.
> .circleci/config.yml: marked executable but has no (or invalid) shebang!
>   If it isn't supposed to be executable, try: `chmod -x .circleci/config.yml`
>   If it is supposed to be executable, double-check its shebang.
> LICENSE: marked executable but has no (or invalid) shebang!
>   If it isn't supposed to be executable, try: `chmod -x LICENSE`
>   If it is supposed to be executable, double-check its shebang.
> .editorconfig: marked executable but has no (or invalid) shebang!
>   If it isn't supposed to be executable, try: `chmod -x .editorconfig`
>   If it is supposed to be executable, double-check its shebang.
> .github/workflows/codeql-analysis.yml: marked executable but has no (or invalid) shebang!
>   If it isn't supposed to be executable, try: `chmod -x .github/workflows/codeql-analysis.yml`
>   If it is supposed to be executable, double-check its shebang.
> .github/ISSUE_TEMPLATE/bug_report.md: marked executable but has no (or invalid) shebang!
>   If it isn't supposed to be executable, try: `chmod -x .github/ISSUE_TEMPLATE/bug_report.md`
>   If it is supposed to be executable, double-check its shebang.
> .github/linters/.yaml-lint.yml: marked executable but has no (or invalid) shebang!
>   If it isn't supposed to be executable, try: `chmod -x .github/linters/.yaml-lint.yml`
>   If it is supposed to be executable, double-check its shebang.
> codespell.txt: marked executable but has no (or invalid) shebang!
>   If it isn't supposed to be executable, try: `chmod -x codespell.txt`
>   If it is supposed to be executable, double-check its shebang.
> CODEOWNERS: marked executable but has no (or invalid) shebang!
>   If it isn't supposed to be executable, try: `chmod -x CODEOWNERS`
>   If it is supposed to be executable, double-check its shebang.
> .github/workflows/super-linter.yml: marked executable but has no (or invalid) shebang!
>   If it isn't supposed to be executable, try: `chmod -x .github/workflows/super-linter.yml`
>   If it is supposed to be executable, double-check its shebang.
> .github/linters/.markdown-lint.yml: marked executable but has no (or invalid) shebang!
>   If it isn't supposed to be executable, try: `chmod -x .github/linters/.markdown-lint.yml`
>   If it is supposed to be executable, double-check its shebang.
> CNAME: marked executable but has no (or invalid) shebang!
>   If it isn't supposed to be executable, try: `chmod -x CNAME`
>   If it is supposed to be executable, double-check its shebang.
> README.md: marked executable but has no (or invalid) shebang!
>   If it isn't supposed to be executable, try: `chmod -x README.md`
>   If it is supposed to be executable, double-check its shebang.
> ```
> 
> Hi @jbampton , @BaseMax .Thank you for your reviews. These are the logs of the pre-commit (where it fails exactly). I cannot fix these problems, in fact, none of my previous commits has any relation to these files, and I didn't change them ever. I don't know exactly how to resolve this issue for my PR, but I can tell that maybe the pre-commit needs some changes, especially for the .github folder.

you can check in this quote the problem that I had previously because of that.

**Review by jbampton — APPROVED** [review]
Max approved so I will.

I will re-add the missing files

**Pull request merged**
