### PR TITLE
Updated footer copyright to show current year

### PR DESCRIPTION
**Pull request by tHe-AK**
Before:
image

Now:
image

### CODE REVIEW

**Comment by BaseMax** [comment]
Dear Akshay;
Hi

Thank you. It was good PR.
Can you introduction yourself? Are you a front-end developer?

Best

**Review by BaseMax — APPROVED** [review]
Approve, Thank you so much.

**Comment by jbampton** [comment]
Hey @BaseMax, @tHe-AK is my friend from Upwork

**Comment by jbampton** [comment]
Don't worry about the spelling I need to fix that

**Comment by jbampton** [comment]
I need to exclude a folder

**Comment by BaseMax** [comment]
It's great. glad to meet him at here. @jbampton

**Comment by jbampton** [comment]
My mistake I need to remove the CPP check was a copy and paste error

**Comment by tHe-AK** [comment]
Hi @BaseMax,
I primarily worked on the frontend but do have some experience in the backend(Java) as well.

**Comment by jbampton** [comment]
The Super Linter has some failures for Markdown lint.  

I need to either remove the check and use pre-commit or exclude the `js/plugins` folder from linting

**Comment by BaseMax** [comment]
Thank you for your message. 
I would like to know more about your frontend experience. If it's possible. (ReactJS/VueJS/gatsby/...)

**Review by jbampton — APPROVED** [review]

**Comment by tHe-AK** [comment]
> Thank you for your message.
> I would like to know more about your frontend experience. If it's possible. (ReactJS/VueJS/gatsby/...)

Sure, I have ~3 years of experience working in Angular. I work as a full-stack developer for a product-based organization.

**Pull request merged**
