### PR TITLE
React.js + Next.js app

### PR DESCRIPTION
**Pull request by uzproblue**
deleted old files
added new next.js app

### CODE REVIEW

**Comment by BaseMax** [comment]
Thanks for the PR.

I think we need to set ES version. so please create ".jshintrc" file and put:
```JSON
{
  "esversion": 6
}
```

**Comment by BaseMax** [comment]
Thanks

**Comment by jbampton** [comment]
This was not done properly as the files we needed for `hound` and `pre-commit` were deleted

**Comment by BaseMax** [comment]
Thanks John, I removed files of old theme, so currently `master` branch is ready for reactjs project.
@uzproblue Please fork again and copy your react project files here. (Remember: not remove any config files)

Thanks, Looking for your next PR.

**Pull request merged**
